FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY McpServer McpServer/
COPY Domain Domain/
RUN dotnet restore McpServer/McpServer.csproj
COPY . .
WORKDIR /src/McpServer
RUN dotnet publish -c Release -o /app/publish 

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["./McpServer"]